spring:
  datasource:
    url: jdbc:mysql://192.168.1.2:3306/flas
    username: root
    password: 518518
  redis:
    database: 0
    host: 192.168.1.6
#    password: 518518
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: 500
        max-idle: 8
        min-idle: 1




